name: Build and Push Docker Image

on:
  push:
    branches:
      - ecolio_api_deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: redacodes/ecolio-api:latest

      - name: Deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull redacodes/ecolio-api:latest
            docker stop api-v1 || true
            docker rm api-v1 || true
            docker run --env-file ~/.env -d --name api-v1 redacodes/ecolio-api:latest
